import Link from 'next/link';
import Visual from '@/components/Visual';
import { SAMPLE } from '@/lib/sample';

const SITE_URL = 'https://www.vidvisual.xyz';

export const metadata = {
  title: 'YouTube to PDF (AI) — Convert YouTube Videos to PDF Notes in 20s | Vid Visual',
  description:
    'Convert YouTube videos, lectures, and podcasts into downloadable PDF study notes in 20 seconds. Clean visual concept cards, vector mind maps, and bulleted takeaways ready to print or annotate on iPad.',
  keywords: [
    'youtube to pdf',
    'convert youtube video to pdf notes',
    'youtube transcript to pdf',
    'download youtube summary as pdf',
    'youtube lecture to pdf notes',
    'free youtube to pdf converter ai',
    'ai video notes pdf',
    'youtube to goodnotes pdf',
    'print youtube summary pdf',
    'youtube study notes pdf',
  ],
  alternates: {
    canonical: `${SITE_URL}/youtube-to-pdf`,
  },
  openGraph: {
    title: 'YouTube to PDF (AI) — Convert YouTube Videos to PDF Notes in 20s',
    description:
      'Convert YouTube videos into formatted PDF notes with whiteboard concept cards, mind maps, and key takeaways in 20 seconds.',
    url: `${SITE_URL}/youtube-to-pdf`,
    siteName: 'Vid Visual',
    type: 'website',
    images: [
      {
        url: `${SITE_URL}/og-image.jpg?v=2`,
        width: 1200,
        height: 630,
        alt: 'Vid Visual — YouTube to PDF AI Notes',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'YouTube to PDF (AI) — Convert YouTube Videos to PDF Notes in 20s',
    description:
      'Convert YouTube videos into formatted PDF notes with whiteboard concept cards, mind maps, and key takeaways in 20 seconds.',
    images: [`${SITE_URL}/og-image.jpg?v=2`],
  },
};

const FAQ_PDF = [
  [
    'How do I convert a YouTube video to a PDF using AI?',
    'Paste any YouTube video link into Vid Visual. The AI engine extracts the main key points from the transcript and generates structured visual concept cards and a connected mind map. Once generated, click the Export button and select Download PDF to receive a formatted, printable study document in seconds.',
  ],
  [
    'Can I import the generated PDF into GoodNotes, Notability, or Notion?',
    'Yes! The PDF files generated by Vid Visual are standard vector PDF documents formatted with clean margins. You can import them directly into tablet note-taking apps like GoodNotes, Notability, Apple Freeform, or attach them to Notion, Obsidian, and Roam Research pages.',
  ],
  [
    'Does the YouTube to PDF converter work on mobile and iPad?',
    'Yes. Vid Visual is fully responsive and runs in any mobile or tablet web browser. You can paste a YouTube link on your iPhone, Android, iPad, or laptop and download the PDF note immediately.',
  ],
  [
    'Is the YouTube to PDF conversion free?',
    'Yes. Vid Visual offers a 100% free plan giving you 3 visual summaries every week forever. Users can preview and download notes without needing to enter a credit card.',
  ],
  [
    'Can I convert 2-hour and multi-hour lectures to PDF?',
    'Yes! Vid Visual specializes in long-form video compression. It reads through multi-hour university lectures and long technical podcasts, distilling the entire session into a clean, concise multi-page or one-page visual PDF.',
  ],
];

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: FAQ_PDF.map(([q, a]) => ({
    '@type': 'Question',
    name: q,
    acceptedAnswer: { '@type': 'Answer', text: a },
  })),
};

const breadcrumbJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: SITE_URL },
    { '@type': 'ListItem', position: 2, name: 'YouTube to PDF', item: `${SITE_URL}/youtube-to-pdf` },
  ],
};

const howToJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Convert Any YouTube Video into a Printable PDF Note',
  description: 'Easily turn YouTube videos into visual PDF documents with AI in under 20 seconds.',
  totalTime: 'PT20S',
  step: [
    {
      '@type': 'HowToStep',
      position: 1,
      name: 'Copy Video Link',
      text: 'Copy the URL of any captioned YouTube video or lecture you want to convert to PDF.',
    },
    {
      '@type': 'HowToStep',
      position: 2,
      name: 'Paste into Vid Visual',
      text: 'Paste the link into Vid Visual and click generate.',
    },
    {
      '@type': 'HowToStep',
      position: 3,
      name: 'AI Synthesizes Visual Cards',
      text: 'Our AI processes the transcript and structures concepts into visual cards and mind maps in ~20s.',
    },
    {
      '@type': 'HowToStep',
      position: 4,
      name: 'Download PDF',
      text: 'Click the Export button and select Download PDF to save your presentation-ready study notes.',
    },
  ],
};

export default function YouTubeToPdfPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToJsonLd) }} />

      <nav className="nav">
        <Link href="/" className="brand vv-hand">
          <img src="/logo.png" alt="Vid Visual" className="brand-icon" width="32" height="32" />
          <span>Vid Visual</span>
        </Link>
        <div className="nav-links">
          <Link href="/#formats">Formats</Link>
          <Link href="/#pricing">Pricing</Link>
          <Link href="/#faq">FAQ</Link>
          <Link href="/login">Log in</Link>
          <Link href="/register" className="btn btn-primary btn-sm">Try it Free</Link>
        </div>
      </nav>

      <div className="breadcrumb-nav">
        <Link href="/">Home</Link>
        <span>&rsaquo;</span>
        <span>YouTube to PDF</span>
      </div>

      <header className="hero">
        <div className="hero-copy">
          <div className="hero-pill" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '6px 14px', borderRadius: '999px', background: 'rgba(239, 68, 68, 0.1)', color: 'var(--red)', fontWeight: 700, fontSize: '0.85rem', marginBottom: '14px', border: '1.5px solid var(--red)' }}>
            <span>📄 Vector PDF Exporter</span>
            <span>·</span>
            <span>Tablet &amp; Print Ready</span>
          </div>
          <h1 className="vv-hand">Convert YouTube Videos to PDF Notes in 20 Seconds</h1>
          <p>
            Turn long YouTube videos, university lectures, and podcast tutorials into clean, presentation-ready
            PDF study notes. Complete with structured whiteboard concept cards, connected mind maps, and actionable takeaways.
          </p>
          <div className="hero-cta">
            <Link href="/register" className="btn btn-primary btn-lg">Convert video to PDF free</Link>
            <a href="#pdf-features" className="link small">See PDF features &darr;</a>
          </div>
          <span className="muted small">100% Free · 3 summaries every week · No credit card required</span>
        </div>
        <div className="hero-demo">
          <Visual data={SAMPLE} format="whiteboard" />
        </div>
      </header>

      {/* Stats Strip */}
      <section className="stats-strip" aria-label="PDF Benchmarks">
        <div className="stat-pill">
          <span className="stat-pill-num">20 Sec</span>
          <span className="stat-pill-label">To distill and generate PDF notes</span>
        </div>
        <div className="stat-pill">
          <span className="stat-pill-num">Vector PDF</span>
          <span className="stat-pill-label">Crystal clear zoom without pixelation</span>
        </div>
        <div className="stat-pill">
          <span className="stat-pill-num">90% Saved</span>
          <span className="stat-pill-label">Study time saved on long videos</span>
        </div>
        <div className="stat-pill">
          <span className="stat-pill-num">100% Free</span>
          <span className="stat-pill-label">3 summaries/week with zero card needed</span>
        </div>
      </section>

      {/* AEO: Direct Answer Block */}
      <section className="answer-box" aria-label="AI Answer Overview">
        <span className="answer-badge">AI Answer Overview</span>
        <h2>How do you convert a YouTube video to a PDF?</h2>
        <p>
          To convert a YouTube video into a PDF document, copy the video link and paste it into <strong>Vid Visual</strong>.
          The AI engine analyzes the transcript, discards conversational fluff and sponsor advertisements,
          and arranges the key ideas into visual concept cards and an interactive mind map.
          You can then download the complete summary as a vector PDF ready to print or annotate on an iPad.
        </p>
        <div className="answer-highlights">
          <div className="answer-highlight">
            <strong>⏱️ Speed</strong>
            <span>Generates complete visual notes in under 20 seconds</span>
          </div>
          <div className="answer-highlight">
            <strong>📱 Tablet Ready</strong>
            <span>Directly import into GoodNotes, Notability &amp; Apple Notes</span>
          </div>
          <div className="answer-highlight">
            <strong>🖨️ Printable</strong>
            <span>Clean contrast and high-resolution typography for paper printing</span>
          </div>
          <div className="answer-highlight">
            <strong>🧩 Structured</strong>
            <span>Includes color-coded concept cards and interconnected mind maps</span>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="section" id="pdf-features" aria-label="PDF Features">
        <h2 className="vv-hand">Why Vid Visual PDF Notes are Built for Serious Learners</h2>
        <div className="grid-3">
          <div className="card">
            <span className="step-num">01</span>
            <h3>No More Messy Screenshots</h3>
            <p>
              Stop pausing YouTube every 30 seconds to take blurry screenshots of slides. Vid Visual extracts the core concepts into beautifully styled visual cards.
            </p>
          </div>
          <div className="card">
            <span className="step-num">02</span>
            <h3>GoodNotes &amp; Notion Ready</h3>
            <p>
              Import your PDF directly into iPad handwriting apps like GoodNotes or embed it cleanly into Notion workspaces as permanent study reference sheets.
            </p>
          </div>
          <div className="card">
            <span className="step-num">03</span>
            <h3>Spatial Mind Map Included</h3>
            <p>
              Every PDF summary includes both structured concept cards and an interconnected vector node map showing how all main ideas relate to each other.
            </p>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="section faq">
        <h2 className="vv-hand">Frequently Asked Questions</h2>
        {FAQ_PDF.map(([q, a]) => (
          <details key={q}>
            <summary>{q}</summary>
            <p>{a}</p>
          </details>
        ))}
      </section>

      {/* CTA */}
      <section className="section final">
        <h2 className="vv-hand">Ready to convert YouTube videos to PDF notes?</h2>
        <Link href="/register" className="btn btn-primary btn-lg">Start Converting Free</Link>
      </section>

      <footer className="site-foot">
        <span className="vv-hand brand-inline">
          <img src="/logo.png" alt="" className="brand-icon-sm" width="22" height="22" /> Vid Visual
        </span>
        <div className="foot-links">
          <Link href="/">Home</Link>
          <Link href="/youtube-video-summarizer">Video Summarizer</Link>
          <Link href="/youtube-to-pdf">YouTube to PDF</Link>
          <Link href="/youtube-podcast-summarizer">Podcast Summarizer</Link>
          <Link href="/youtube-lecture-summarizer">Lecture Summaries</Link>
          <Link href="/youtube-to-mind-map">Mind Maps</Link>
          <Link href="/video-to-infographic">Infographics</Link>
          <Link href="/youtube-to-notes">Study Notes</Link>
          <a href="mailto:vidvisual.xyz@gmail.com">Support</a>
        </div>
        <span className="muted small">© {new Date().getFullYear()} Vid Visual</span>
      </footer>
    </>
  );
}
