import Link from 'next/link';
import Visual from '@/components/Visual';
import { SAMPLE } from '@/lib/sample';

const SITE_URL = 'https://www.vidvisual.xyz';

export const metadata = {
  title: 'Whiteboard Video Summarizer — AI Whiteboard Notes from YouTube | Vid Visual',
  description:
    'Turn any YouTube video, podcast, or lecture into an interactive whiteboard visual summary in 20 seconds. Scannable concept cards and spatial mind maps generated by AI. Free to start.',
  keywords: [
    'whiteboard video summary',
    'youtube whiteboard summary',
    'visual video summarizer',
    'whiteboard notes from video',
    'ai whiteboard summary generator',
    'visual youtube summary',
    'whiteboard note taking ai',
    'free whiteboard summarizer',
  ],
  alternates: {
    canonical: `${SITE_URL}/whiteboard-summary`,
  },
  openGraph: {
    title: 'Whiteboard Video Summarizer — AI Whiteboard Notes from YouTube',
    description:
      'Transform complex YouTube videos into scannable whiteboard visual summaries in under 20 seconds with AI.',
    url: `${SITE_URL}/whiteboard-summary`,
    siteName: 'Vid Visual',
    type: 'website',
    images: [
      {
        url: `/og-image.jpg?v=2`,
        width: 1200,
        height: 630,
        alt: 'Vid Visual — AI Whiteboard Video Summarizer',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Whiteboard Video Summarizer — AI Whiteboard Notes from YouTube',
    description:
      'Transform complex YouTube videos into scannable whiteboard visual summaries in under 20 seconds with AI.',
    images: [`/og-image.jpg?v=2`],
  },
};

const FAQ_WHITEBOARD = [
  [
    'What is an AI whiteboard video summary?',
    'A whiteboard video summary organizes spoken information into visual concept cards, spatial relationships, and clear takeaways laid out on a digital canvas resembling a whiteboard. This visual format reduces cognitive overload and accelerates learning.',
  ],
  [
    'How does Vid Visual draw the whiteboard?',
    'Vid Visual extracts the full transcript from your YouTube link, uses Gemini AI to identify the underlying concept network, and renders custom SVG mind maps and hand-styled concept cards.',
  ],
  [
    'Can I customize the whiteboard theme?',
    'Yes, Vid Visual offers custom visual palettes including Marker, Ocean, Forest, Sunset, and Slate, allowing you to match your personal study style or brand.',
  ],
  [
    'Can I download the whiteboard as an image or PDF?',
    'Yes, download your whiteboard summaries as standard JPG, high-resolution HD PNG, or vector PDF documents with no watermark on paid plans.',
  ],
];

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: FAQ_WHITEBOARD.map(([q, a]) => ({
    '@type': 'Question',
    name: q,
    acceptedAnswer: { '@type': 'Answer', text: a },
  })),
};

const breadcrumbJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: SITE_URL },
    { '@type': 'ListItem', position: 2, name: 'Whiteboard Summary', item: `${SITE_URL}/whiteboard-summary` },
  ],
};

const howToJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Generate a Whiteboard Visual Summary from YouTube',
  description: 'Create a whiteboard visual summary from any YouTube video in 3 simple steps.',
  totalTime: 'PT1M',
  step: [
    {
      '@type': 'HowToStep',
      position: 1,
      name: 'Copy Video Link',
      text: 'Copy any YouTube URL with subtitles or captions.',
    },
    {
      '@type': 'HowToStep',
      position: 2,
      name: 'Select Whiteboard Format',
      text: 'Paste into Vid Visual and choose the Whiteboard format.',
    },
    {
      '@type': 'HowToStep',
      position: 3,
      name: 'Export Your Whiteboard',
      text: 'Review the visual canvas and download as HD PNG or PDF.',
    },
  ],
};

export default function WhiteboardSummaryPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToJsonLd) }}
      />

      <nav className="nav">
        <Link href="/" className="brand vv-hand"><img src="/logo.png" alt="Vid Visual" className="brand-icon" width="32" height="32" /><span>Vid Visual</span></Link>
        <div className="nav-links">
          <Link href="/youtube-to-mind-map">Mind Maps</Link>
          <Link href="/youtube-to-notes">Study Notes</Link>
          <Link href="/#pricing">Pricing</Link>
          <Link href="/login">Log in</Link>
          <Link href="/register" className="btn btn-primary btn-sm">Try it Free</Link>
        </div>
      </nav>

      <div className="breadcrumb-nav">
        <Link href="/">Home</Link>
        <span>&rsaquo;</span>
        <span>Whiteboard Video Summary</span>
      </div>

      <header className="hero">
        <div className="hero-copy">
          <div className="hero-pill" style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', padding: '6px 14px', borderRadius: '999px', background: 'rgba(43, 89, 224, 0.1)', color: 'var(--blue)', fontWeight: 700, fontSize: '0.85rem', marginBottom: '14px', border: '1.5px solid var(--blue)' }}>
            <span>🖊️ Interactive Whiteboard AI</span>
            <span>·</span>
            <span>Spatial Knowledge Maps</span>
          </div>
          <h1 className="vv-hand">AI Whiteboard Visual Summaries from Any YouTube Video in 20 Seconds</h1>
          <p>
            Experience the clarity of a physical whiteboard session without doing the drawing yourself.
            Vid Visual turns complex video lectures, podcasts, and talks into structured concept cards and visual mind maps in 20 seconds.
          </p>
          <div className="hero-cta">
            <Link href="/register" className="btn btn-primary btn-lg">Create Whiteboard Free</Link>
            <a href="#how" className="link small">See how it works &darr;</a>
          </div>
          <span className="muted small">Free: 3 whiteboard summaries/week · No card required</span>
        </div>
        <div className="hero-demo">
          <Visual data={SAMPLE} format="whiteboard" theme="marker" />
        </div>
      </header>

      {/* Stats Strip */}
      <section className="stats-strip" aria-label="Whiteboard Benchmarks">
        <div className="stat-pill">
          <span className="stat-pill-num">20 Sec</span>
          <span className="stat-pill-label">Average whiteboard drawing speed</span>
        </div>
        <div className="stat-pill">
          <span className="stat-pill-num">65% Higher</span>
          <span className="stat-pill-label">Retention compared to plain text reading</span>
        </div>
        <div className="stat-pill">
          <span className="stat-pill-num">5 Palettes</span>
          <span className="stat-pill-label">Marker, Ocean, Forest, Sunset, Slate</span>
        </div>
        <div className="stat-pill">
          <span className="stat-pill-num">100% Free</span>
          <span className="stat-pill-label">3 summaries/week with zero card needed</span>
        </div>
      </section>

      {/* Direct Answer Box for AEO */}
      <section className="answer-box" aria-label="Direct Answer Overview">
        <span className="answer-badge">AI Answer Overview</span>
        <h2>What is a whiteboard video summary?</h2>
        <p>
          A <strong>whiteboard video summary</strong> is a spatial, visual note format that breaks down a video into
          color-coded concept cards, an interconnected mind map, and high-yield takeaways.
          Unlike traditional text-only summaries, a whiteboard visual organizes ideas spatially,
          allowing users to understand and memorize a 60-minute video in under 60 seconds.
        </p>
        <div className="answer-highlights">
          <div className="answer-highlight">
            <strong>🎨 Canvas Style</strong>
            <span>Hand-crafted whiteboard cards & mind map</span>
          </div>
          <div className="answer-highlight">
            <strong>⏱️ Speed</strong>
            <span>Processed in under 60 seconds</span>
          </div>
          <div className="answer-highlight">
            <strong>📥 Export</strong>
            <span>JPG, HD PNG, and vector PDF</span>
          </div>
        </div>
      </section>

      {/* Why Whiteboards Work */}
      <section className="section">
        <h2 className="vv-hand">The Power of Visual Spatial Learning</h2>
        <p className="section-lead">Why spatial whiteboards beat scrubbing through 40-minute videos:</p>
        <div className="card-grid">
          <div className="info-card accent-blue">
            <span className="card-emoji">💡</span>
            <h3>Bite-Sized Concept Cards</h3>
            <p>Every major topic gets its own card with a memorable emoji and clear, concise explanation.</p>
          </div>
          <div className="info-card accent-green">
            <span className="card-emoji">🕸️</span>
            <h3>Connected Knowledge Hub</h3>
            <p>See the relationships and hierarchy between ideas so you remember the whole story, not just fragments.</p>
          </div>
          <div className="info-card accent-amber">
            <span className="card-emoji">🎨</span>
            <h3>Multiple Visual Themes</h3>
            <p>Switch between Marker, Ocean, Forest, Sunset, and Slate themes to match your study environment.</p>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how" className="section how">
        <h2 className="vv-hand">3 Simple Steps to Your Whiteboard</h2>
        <div className="steps-detailed">
          <div className="step-detailed">
            <div className="step-num vv-hand">1</div>
            <div>
              <h3>Copy video link</h3>
              <p>Grab any YouTube link that has captions turned on.</p>
            </div>
          </div>
          <div className="step-detailed">
            <div className="step-num vv-hand">2</div>
            <div>
              <h3>Paste into Vid Visual</h3>
              <p>Choose the Whiteboard format and click Generate.</p>
            </div>
          </div>
          <div className="step-detailed">
            <div className="step-num vv-hand">3</div>
            <div>
              <h3>Study or export</h3>
              <p>Review your whiteboard summary, or download as an HD PNG or PDF.</p>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="section faq">
        <h2 className="vv-hand">Frequently Asked Questions</h2>
        {FAQ_WHITEBOARD.map(([q, a]) => (
          <details key={q}>
            <summary>{q}</summary>
            <p>{a}</p>
          </details>
        ))}
      </section>

      {/* CTA */}
      <section className="section final">
        <h2 className="vv-hand">Ready to turn videos into whiteboards?</h2>
        <Link href="/register" className="btn btn-primary btn-lg">Make Free Whiteboard</Link>
      </section>

      <footer className="site-foot">
        <span className="vv-hand brand-inline">
          <img src="/logo.png" alt="" className="brand-icon-sm" width="22" height="22" /> Vid Visual
        </span>
        <div className="foot-links">
          <Link href="/">Home</Link>
          <Link href="/youtube-podcast-summarizer">Podcasts</Link>
          <Link href="/youtube-lecture-summarizer">Lectures</Link>
          <Link href="/video-to-infographic">Infographics</Link>
          <Link href="/youtube-to-mind-map">Mind Maps</Link>
          <Link href="/youtube-to-notes">Study Notes</Link>
          <a href="mailto:vidvisual.xyz@gmail.com">Support</a>
        </div>
        <span className="muted small">© {new Date().getFullYear()} Vid Visual</span>
      </footer>
    </>
  );
}
